name: jerry
description: Jerry - AI Dev Assistant (Ultra)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.7
  flutter_code_editor: ^1.0.6
  highlight: ^0.7.0
  path_provider: ^2.0.11
  permission_handler: ^10.4.0
  speech_to_text: ^6.5.0
  http: ^0.13.6
  file_picker: ^5.2.4
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
